import "./styles.css";

const app=document.querySelector("#app");
app.innerHTML=`
<div class="loader"><div class="loader__line"></div><span>SKYHAVEN ESTATES</span></div><div class="cursor"></div><div class="cursor-dot"></div><div class="progress"></div>
<header class="header"><a class="brand magnetic" href="#top">SKYHAVEN <span>ESTATES</span></a><button class="menu-toggle magnetic" aria-label="Toggle navigation"><span></span><span></span></button><nav class="nav"><a href="#estate">The Estate</a><a href="#architecture">Architecture</a><a href="#experience">Experience</a><a href="#view">The View</a><a href="#concept">Concept</a></nav><a class="header-cta magnetic" href="#concept">Explore the vision <span>↗</span></a></header>
<main id="top">
<section class="hero"><div class="hero__media"></div><div class="hero__veil"></div><div class="hero__content"><p class="eyebrow reveal">MOUNTAIN-SIDE RESIDENCE <i></i> CONCEPT 01</p><h1 class="hero__title reveal">A Home<br><em>Above</em> Everything.</h1><div class="hero__bottom reveal"><p>Set high on the side of a mountain,<br>designed as an escape from everything below it.</p><a class="circle-link magnetic" href="#estate">↓</a></div></div><div class="hero__coordinates">46° 32' 18" N <span>/</span> 9° 49' 02" E</div></section>
<section class="intro section-pad" id="estate"><div class="section-index">01 / 06</div><div class="intro__copy reveal"><p class="eyebrow">THE ESCAPE</p><h2>Come home to a<br><em>different perspective.</em></h2><p class="large-copy">Skyhaven Estates is not meant to feel like just another luxury property. It is meant to feel like the place you would want to return to after a long day in the real world.</p></div><div class="intro__aside reveal"><span>QUIET.</span><span>ELEVATED.</span><span>UNINTERRUPTED.</span></div></section>
<section class="image-break" id="architecture"><div class="image-break__media"></div><div class="image-break__label reveal">ARCHITECTURE / 02</div><div class="image-break__quote reveal">“A little out of reach.<br><em>Instantly familiar.</em>”</div></section>
<section class="residence section-pad"><div class="section-index">03 / 06</div><div class="residence__heading reveal"><p class="eyebrow">THE RESIDENCE</p><h2>Designed to<br><em>feel unreal.</em></h2></div><div class="residence__text reveal"><p>Every line is intentional. Every opening frames the landscape. Warm stone, quiet timber and expansive glass create a home that feels cinematic without ever feeling cold.</p><a class="text-link magnetic" href="#experience">Discover the experience <span>↗</span></a></div></section>
<section class="gallery"><div class="gallery__track"><figure class="gallery-card gallery-card--wide"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=85" alt="Luxury modern interior" loading="lazy"><figcaption><span>01</span> The interior</figcaption></figure><figure class="gallery-card"><img src="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=85" alt="Minimal luxury living space" loading="lazy"><figcaption><span>02</span> Space & light</figcaption></figure><figure class="gallery-card gallery-card--tall"><img src="https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=85" alt="Contemporary architectural detail" loading="lazy"><figcaption><span>03</span> Material language</figcaption></figure><figure class="gallery-card"><img src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85" alt="Mountain luxury residence" loading="lazy"><figcaption><span>04</span> The residence</figcaption></figure></div></section>
<section class="view section-pad" id="view"><div class="view__image reveal"></div><div class="view__content reveal"><div class="section-index">04 / 06</div><p class="eyebrow">THE VIEW</p><h2>Where everything<br><em>slows down.</em></h2><p>Surrounded by space, light, and the kind of views that make everything else slow down for a minute.</p><div class="view__meta"><span>DAWN — 05:42</span><span>HEIGHT — 2,180 M</span></div></div></section>
<section class="experience section-pad" id="experience"><div class="section-index">05 / 06</div><div class="experience__intro reveal"><p class="eyebrow">THE EXPERIENCE</p><h2>More than a<br><em>luxury property.</em></h2></div><div class="experience__grid"><article class="detail reveal"><span>01</span><h3>Space</h3><p>Rooms that breathe. Openings that disappear into the landscape.</p></article><article class="detail reveal"><span>02</span><h3>Light</h3><p>Morning sun across stone. Golden hours without a schedule.</p></article><article class="detail reveal"><span>03</span><h3>Silence</h3><p>No traffic. No rush. Just the sound of wind moving through the trees.</p></article><article class="detail reveal"><span>04</span><h3>Return</h3><p>The feeling of arriving somewhere you never want to leave.</p></article></div></section>
<section class="concept section-pad" id="concept"><div class="concept__top"><div class="section-index">06 / 06</div><p class="eyebrow">A CONCEPT</p></div><div class="concept__body"><h2 class="reveal">Not a listing.<br><em>A vision.</em></h2><div class="concept__copy reveal"><p>Skyhaven Estates is not a real listing. It is a concept. But that is what makes it fun.</p><p>The goal was to create something that feels almost unreal in the best way. A home that feels cinematic. Peaceful. A little out of reach. And still instantly familiar as the kind of place anyone would want to call home.</p></div></div></section>
<section class="final"><div class="final__media"></div><div class="final__veil"></div><div class="final__content reveal"><p class="eyebrow">THE DREAM</p><h2>Imagine coming<br><em>home here.</em></h2><a class="final-link magnetic" href="#top">Begin again <span>↑</span></a></div><div class="final__footer"><span>SKYHAVEN ESTATES</span><span>PURE ESCAPE, ELEVATED.</span></div></section></main>`;
const cursor=document.querySelector(".cursor"),dot=document.querySelector(".cursor-dot"),loader=document.querySelector(".loader");window.addEventListener("load",()=>setTimeout(()=>loader.classList.add("is-hidden"),500));window.addEventListener("scroll",()=>{const max=document.documentElement.scrollHeight-innerHeight;document.querySelector(".progress").style.transform=`scaleX(${max>0?scrollY/max:0})`;document.querySelector(".header").classList.toggle("is-scrolled",scrollY>40)});
const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("is-visible")),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener("click",e=>{const t=document.querySelector(a.getAttribute("href"));if(!t)return;e.preventDefault();t.scrollIntoView({behavior:"smooth",block:"start"});document.querySelector(".nav")?.classList.remove("is-open")}));
const menu=document.querySelector(".menu-toggle"),nav=document.querySelector(".nav");menu.addEventListener("click",()=>nav.classList.toggle("is-open"));
if(matchMedia("(pointer:fine)").matches){addEventListener("mousemove",e=>{cursor.style.transform=`translate3d(${e.clientX}px,${e.clientY}px,0)`;dot.style.transform=`translate3d(${e.clientX}px,${e.clientY}px,0)`});document.querySelectorAll("a,button,.magnetic").forEach(el=>{el.addEventListener("mouseenter",()=>cursor.classList.add("is-hover"));el.addEventListener("mouseleave",()=>cursor.classList.remove("is-hover"))});document.querySelectorAll(".magnetic").forEach(el=>{el.addEventListener("mousemove",e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.12,y=(e.clientY-r.top-r.height/2)*.12;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener("mouseleave",()=>el.style.transform="")})}
const hero=document.querySelector(".hero__media");addEventListener("scroll",()=>{if(scrollY<innerHeight*1.2)hero.style.transform=`scale(1.04) translateY(${scrollY*.08}px)`});
const gallery=document.querySelector(".gallery__track");if(gallery){let targetX=0,currentX=0;const update=()=>{const max=Math.max(0,gallery.scrollWidth-innerWidth);targetX=Math.min(max,Math.max(0,scrollY-gallery.parentElement.offsetTop))*.7;currentX+=(targetX-currentX)*.08;gallery.style.transform=`translate3d(${-currentX}px,0,0)`;requestAnimationFrame(update)};requestAnimationFrame(update)}
